---
title: "Data used in these tutorials"
tbl-cap-location: top
---

During the tutorials, we will use a dataset containing social and ecological variables associated with agricultural systems (coffee production). The variables are classified into four main groups:

-   Farm structure, management, and production

-   Access to knowledge and subsidies

-   Soil characteristics

-   Plant variables

Analysis of this data can contribute to the development of more sustainable and diversified agroecosystems. The list of variables with their descriptions and units is provided in @tbl-overviewdata. The data file is available on Brightspace.

| Variable group | Variable name | Description | Units |
|------------------|------------------|------------------|------------------|
| Farm structure, management, and production | municipality | Municipality | \- |
| Farm structure, management, and production | farm_size | Size of the farm | ha |
| Farm structure, management, and production | altitude | Average altitude of the farm | m |
| Farm structure, management, and production | farm_type | Farm type: Conventional (con); Agroecological (eco); or large-scale (large) | \- |
| Farm structure, management, and production | manure | Total manure used as fertilizer | kg/ha/year |
| Farm structure, management, and production | pesticide | Quantity of active ingredients (pesticides) applied | g/ha/year |
| Farm structure, management, and production | Pmin | Mineral phosphorus input (fertilizer) | kg/ha/year |
| Farm structure, management, and production | Kmin | Mineral potassium input (fertilizer) | kg/ha/year |
| Farm structure, management, and production | coffee_prod_past | Coffee productivity in 2015 | kg/ha/year |
| Farm structure, management, and production | coffee_prod | Coffee productivity in 2020 | kg/ha/year |
| Farm structure, management, and production | mowing | Mowing intensity | hours/ha/year |
| Access to knowledge and subsidies | n_practices | Total number of agroecological practices adopted | \- |
| Access to knowledge and subsidies | n_ext_projects | Number of CTA projects accessed | \- |
| Access to knowledge and subsidies | policy_access | Policy access (none, low, moderate, or high) | \- |
| Soil characteristics | CMB | Carbon microbial biomass in the soil | µg/g dry soil |
| Soil characteristics | pH | Soil pH in water | \- |
| Soil characteristics | SOM | Soil organic matter | \% |
| Soil characteristics | clay | Soil clay content | kg/kg |
| Soil characteristics | P_soil | Soil available phosphorus | mg/dm³ |
| Soil characteristics | K_soil | Soil available potassium | mg/dm³ |
| Soil characteristics | SB | Sum of bases | cmolc/dm³ |
| Soil characteristics | litter_thickness | Litter thickness | cm |
| Plant variables | tree_cover | Tree cover in the plot | m² |
| Plant variables | tree_density | Number of trees per unit area | /ha |
| Plant variables | total_species | Total number of species found in the plot | \- |
| Plant variables | shannon_PIM | Shannon-Weiner diversity index | \- |
| Plant variables | CWM.SLA | Community weighted mean of specific leaf area | cm²/g |
| Plant variables | CWM.N | Community weighted mean of leaf nitrogen concentration | \% |

: List of variables contained in the dataset used for the tutorials, along with their associated units {#tbl-overviewdata}