---
title: Natural processes
code-tools: false
---

{{< badge programme "Global sustainability science" >}} {{< badge year "Year 1" >}} {{< badge pycoding "Python programming" >}}

## Course code

GEO1-2412

## Course coordinator

[Dr Gerbrand Koren](https://www.uu.nl/medewerkers/GBKoren)

## Course description

The aim of this course is to provide students with a solid natural science base for studying global change. As such, it provides the fundamental understanding of natural processes that are needed as a basis for follow-up courses dealing in depth with specific global change effects, such as Global Climate Change.

We will focus on the Earths' energy balance, the hydrological cycle and the elemental cycles of carbon, nitrogen and phosphorus, because they are essential for life on Earth and are linked to the major global change effects that our society is dealing with today. We will look at the major stocks of energy, water and elements in different environmental compartments (atmosphere, hydrosphere, lithosphere and biosphere), as well as the processes that govern the exchange between those compartments and the storage capacity of the compartments.

## Course objectives